spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/blog?serverTimezone=Asia/Seoul
    username: dante
    password: qhdwnsgud1!
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    open-in-view: true    hibernate:      ddl-auto: update
      naming:        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false  
    properties:      hibernate:
        show_sql: true
        format_sql: true
  jackson:    serialization:      fail-on-empty-beans: false  server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true